version: '3.9'
services:
  web:
    build: .
    container_name: login-page
    ports: "3000:3000"
    depends on: -db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword   # must match db service password
      DB_NAME: login_db
    volumes:
      - .:/app
    restart: always


# MySQL Database
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:



