version: "4.8"

services:
  web:
    build: .
    container_name: login-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: login_db
    volumes:
      - ./public:/app/public   # optional: live sync your frontend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   # persistent volume for MySQL data

volumes:
  db_data:   # Docker-managed volume
